title: "Cecil"
baseline: "Your content driven static site generator."
description: "Cecil is a CLI application that merges plain text files (written in Markdown), images and Twig templates to generate a static website."
baseurl: "https://cecil.app/"
author:
  name: "Arnaud Ligny"
  url: "https://arnaudligny.fr"
keywords: ["static", "generator", "website", "SSG", "PHP", "Twig"]
social:
  twitter:
    site: Cecil_Static
    creator: ArnaudLigny
  github:
    repo: https://github.com/Cecilapp/Cecil
image: /images/cecil-card.png
language: en
languages:
  - code: en
    name: English
    locale: en_US
  - code: fr
    enabled: true
    name: Français
    locale: fr_FR
    config:
      baseline: "Votre générateur de site statique centré sur le contenu."
      description: "Cecil est une application en ligne de commande qui fusionne des fichiers texte (écrits en Markdown), des images et des templates Twig afin de générer un site web statique."
      menus:
        main:
          - id: documentation
            name: Documentation
            weight: 10
        footer:
        - id: github
          url: https://github.com/Cecilapp/
      algolia:
        enabled: false
menus:
  main:
    - id: documentation
      name: Documentation
      weight: 10
    - id: index
      enabled: false
    - id: cms
      enabled: false
    - id: hosting
      enabled: false
  footer:
    - id: github
      url: https://github.com/Cecilapp/
output:
  formats:
    - name: phar
      mediatype: 'application/octet-stream'
      extension: 'phar'
    - name: sha1
      mediatype: 'text/plain'
      extension: 'phar.sha1'
    - name: algolia
      mediatype: 'application/json'
      suffix: 'algolia'
      extension: 'json'
    - name: bash
      mediatype: 'text/plain'
      extension: 'sh'
  pagetypeformats:
    homepage: ['html', 'algolia']
    section: ['html', 'atom']
theme:
  - netlify
netlify:
  redirects:
    - from: https://cecilapp.netlify.app/*
      to: https://cecil.app/:splat
      status: 301
      force: true
static:
  exclude:
    - 'cecil-demo.png'
    - '*.mp4'
release:
  name: cecil.phar
  sha1: cecil.phar.sha1
docs_repo: https://github.com/Cecilapp/Cecil/edit/master/docs/
googleanalytics: UA-387892-21
gsv: LIvUncCjs-xtddzUhv7CNTHWsjXpOk0C4BL4KMRYUVM
highlight:
  version: 10.4.0
  styles: atom-one-dark
  languages: twig
anchor:
  version: 4.3.1
tocbot:
  version: 4.12.3
algolia:
  enabled: true
  version: '@4'
  autocomplete:
    version: 0
  application_id: 'PVTO81KCEC'
  search_api_key: 'd4f7a88b01ac073e9bb24dc264ead2dc'
  index: 'documentation'
alpinejs:
  version: 3.8.1
metatags:
  jsonld: true
