<?php
// Items: [srcKey, mode, h2 title (EN), extra]
//  pre   : file intro (before first h2)
//  body  : whole file
//  keep  : h2 section with its heading
//  whole : h2 section without its heading, sub-headings promoted (extra: h3 titles to skip)
//  intro : h2 section intro only
//  h3    : selected h3 of a h2, promoted (extra: h3 titles)
$t = fn ($en, $fr) => ['en' => $en, 'fr' => $fr];

$spec = [
    'getting-started' => [
        'weight' => 1,
        'index' => [
            'title' => $t('Getting started', 'Bien démarrer'),
            'desc' => $t('Discover Cecil, create your first website in a few minutes and learn how a project is organized.', 'Découvrez Cecil, créez votre premier site web en quelques minutes et comprenez l’organisation d’un projet.'),
            'items' => [['QS', 'pre']],
        ],
        'pages' => [
            'quick-start' => ['w' => 1, 'title' => $t('Quick Start', 'Démarrage rapide'),
                'desc' => $t('Install Cecil, create a new website, add pages, preview it locally, then build and deploy it.', 'Installez Cecil, créez un site, ajoutez des pages, prévisualisez-le localement, puis générez-le et déployez-le.'),
                'items' => [['QS', 'keep', 'Create a website']],
                'alias' => $t('documentation/quick-start', 'documentation/demarrage-rapide'), 'menu' => 'home'],
            'directory-structure' => ['w' => 2, 'title' => $t('Directory structure', 'Structure des dossiers'),
                'desc' => $t('How source files are organized, how the built website looks like and how files are routed to URLs.', 'Organisation des fichiers sources, arborescence du site généré et routage des fichiers vers les URL.'),
                'items' => [['C', 'whole', 'Files organization']]],
            'starter-kits' => ['w' => 3, 'title' => $t('Starter kits', 'Kits de démarrage'),
                'desc' => $t('Get started quickly with a ready-to-use project template.', 'Démarrez rapidement avec un modèle de projet prêt à l’emploi.'),
                'items' => [['QS', 'whole', 'Starter kits']]],
        ],
    ],
    'content' => [
        'weight' => 2,
        'index' => [
            'title' => $t('Content', 'Contenu'),
            'desc' => $t('Create and organize your content: pages, front matter, Markdown, multilingual and dynamic content.', 'Créez et organisez votre contenu : pages, front matter, Markdown, contenu multilingue et dynamique.'),
            'items' => [['C', 'pre']],
            'alias' => ['fr' => 'documentation/contenu'],
        ],
        'pages' => [
            'pages' => ['w' => 1, 'title' => $t('Pages and sections', 'Pages et sections'),
                'desc' => $t('Anatomy of a page, file prefix, sections, sub-sections and home page.', 'Anatomie d’une page, préfixe de fichier, sections, sous-sections et page d’accueil.'),
                'items' => [['C', 'whole', 'Pages'], ['C', 'h3', 'Variables', ['File prefix', 'Section', 'Home page']]]],
            'front-matter' => ['w' => 2, 'title' => $t('Front matter', 'Front matter'),
                'desc' => $t('Custom and predefined page variables: menu, taxonomy, schedule, redirect, alias, output, etc.', 'Variables de page personnalisées et prédéfinies : menu, taxonomie, planification, redirection, alias, sortie, etc.'),
                'items' => [['C', 'whole', 'Variables', ['File prefix', 'Section', 'Home page']]]],
            'markdown' => ['w' => 3, 'title' => $t('Markdown', 'Markdown'),
                'desc' => $t('Markdown syntax and extensions: attributes, links, images, table of contents, notes, syntax highlight, etc.', 'Syntaxe et extensions Markdown : attributs, liens, images, table des matières, notes, coloration syntaxique, etc.'),
                'items' => [['C', 'whole', 'Markdown']]],
            'multilingual' => ['w' => 4, 'title' => $t('Multilingual', 'Multilingue'),
                'desc' => $t('Translate pages through file name or front matter and link translated pages.', 'Traduisez les pages via le nom de fichier ou le front matter et liez les pages traduites.'),
                'items' => [['C', 'whole', 'Multilingual']]],
            'dynamic-content' => ['w' => 5, 'title' => $t('Dynamic content', 'Contenu dynamique'),
                'desc' => $t('Use variables and Twig expressions inside page content.', 'Utilisez des variables et expressions Twig dans le contenu des pages.'),
                'items' => [['C', 'whole', 'Dynamic content']]],
        ],
    ],
    'templates' => [
        'weight' => 3,
        'index' => [
            'title' => $t('Templates', 'Templates'),
            'desc' => $t('Work with Twig layouts, templates and components.', 'Travaillez avec les layouts, templates et composants Twig.'),
            'items' => [['T', 'pre'], ['T', 'keep', 'Example']],
            'alias' => $t('documentation/layouts', 'documentation/layouts'),
        ],
        'pages' => [
            'lookup-rules' => ['w' => 1, 'title' => $t('Organization and lookup rules', 'Organisation et règles de recherche'),
                'desc' => $t('Kinds of templates, naming convention, built-in templates and how a template is chosen for a page.', 'Types de templates, convention de nommage, templates intégrés et choix du template d’une page.'),
                'items' => [['T', 'keep', 'Files organization'], ['T', 'keep', 'Lookup rules']]],
            'variables' => ['w' => 2, 'title' => $t('Variables', 'Variables'),
                'desc' => $t('Variables available in templates: site, page and cecil.', 'Variables disponibles dans les templates : site, page et cecil.'),
                'items' => [['T', 'whole', 'Variables']]],
            'components' => ['w' => 4, 'title' => $t('Components', 'Composants'),
                'desc' => $t('Create reusable template components.', 'Créez des composants de template réutilisables.'),
                'items' => [['T', 'whole', 'Components']]],
            'localization' => ['w' => 5, 'title' => $t('Localization', 'Localisation'),
                'desc' => $t('Translate texts and localize dates in templates.', 'Traduisez les textes et localisez les dates dans les templates.'),
                'items' => [['T', 'whole', 'Localization']]],
            'cache' => ['w' => 6, 'title' => $t('Cache', 'Cache'),
                'desc' => $t('Templates cache and fragments cache.', 'Cache des templates et cache de fragments.'),
                'items' => [['T', 'whole', 'Cache']]],
            'extend' => ['w' => 7, 'title' => $t('Extend', 'Étendre'),
                'desc' => $t('Add custom functions and filters, or use a theme.', 'Ajoutez des fonctions et filtres personnalisés, ou utilisez un thème.'),
                'items' => [['T', 'whole', 'Extend']]],
        ],
    ],
    'templates/reference' => [
        'weight' => 3,
        'index' => [
            'title' => $t('Functions and filters', 'Fonctions et filtres'),
            'desc' => $t('Reference of the Twig functions, sorts and filters provided by Cecil.', 'Référence des fonctions, tris et filtres Twig fournis par Cecil.'),
            'items' => [],
        ],
        'pages' => [
            'functions' => ['w' => 1, 'title' => $t('Functions', 'Fonctions'),
                'desc' => $t('url, html, readtime, hash, cache_key, getenv, dump, etc.', 'url, html, readtime, hash, cache_key, getenv, dump, etc.'),
                'items' => [['T', 'intro', 'Functions'], ['T', 'h3', 'Functions', ['url', 'html', 'readtime', 'hash', 'cache_key', 'getenv', 'dump', 'd']]]],
            'sorts' => ['w' => 2, 'title' => $t('Sorts', 'Tris'),
                'desc' => $t('Sort collections of pages, menus or taxonomies.', 'Triez des collections de pages, menus ou taxonomies.'),
                'items' => [['T', 'whole', 'Sorts']]],
            'filters' => ['w' => 3, 'title' => $t('Filters', 'Filtres'),
                'desc' => $t('filter_by, markdown_to_html, toc, slugify, excerpt, highlight, preg_*, etc.', 'filter_by, markdown_to_html, toc, slugify, excerpt, highlight, preg_*, etc.'),
                'items' => [['T', 'intro', 'Filters'], ['T', 'h3', 'Filters', ['filter_by', 'filter', 'markdown_to_html', 'toc', 'json_decode', 'yaml_parse', 'slugify', 'u', 'singular', 'plural', 'excerpt', 'excerpt_html', 'highlight', 'preg_split', 'preg_match_all', 'hex_to_rgb']]]],
        ],
    ],
    'assets' => [
        'weight' => 4,
        'index' => [
            'title' => $t('Assets', 'Assets'),
            'desc' => $t('Handle assets (images, stylesheets, scripts, etc.) with the asset() function: process, optimize and fingerprint them.', 'Manipulez les assets (images, feuilles de style, scripts, etc.) avec la fonction asset() : traitement, optimisation et empreinte.'),
            'items' => [['T', 'h3', 'Functions', ['asset', 'integrity']]],
        ],
        'pages' => [
            'images' => ['w' => 1, 'title' => $t('Images', 'Images'),
                'desc' => $t('Resize, crop and convert images, generate responsive images and placeholders.', 'Redimensionnez, recadrez et convertissez les images, générez des images responsives et des placeholders.'),
                'items' => [['T', 'h3', 'Functions', ['image_srcset', 'image_sizes', 'image_from_website']], ['T', 'h3', 'Filters', ['resize', 'cover', 'maskable', 'webp', 'avif', 'lqip', 'dominant_color']]]],
            'processing' => ['w' => 2, 'title' => $t('CSS, JavaScript and processing', 'CSS, JavaScript et traitements'),
                'desc' => $t('Compile Sass, minify, fingerprint, inline or embed assets.', 'Compilez Sass, minifiez, ajoutez une empreinte, intégrez ou embarquez les assets.'),
                'items' => [['T', 'h3', 'Filters', ['fingerprint', 'minify', 'minify_css', 'minify_js', 'scss_to_css', 'to_css', 'inline', 'dataurl']]]],
            'cdn-providers' => ['w' => 3, 'title' => $t('CDN providers', 'Fournisseurs de CDN'),
                'desc' => $t('Configuration examples of image CDN providers (Cloudinary, Cloudimage, TwicPics, imgix, Netlify Image CDN).', 'Exemples de configuration de fournisseurs de CDN d’images (Cloudinary, Cloudimage, TwicPics, imgix, Netlify Image CDN).'),
                'items' => [['CDN', 'body']]],
        ],
    ],
    'configuration' => [
        'weight' => 5,
        'index' => [
            'title' => $t('Configuration', 'Configuration'),
            'desc' => $t('Configure your website with cecil.yml, and override it with environment variables or CLI option.', 'Configurez votre site avec cecil.yml, et surchargez-le avec des variables d’environnement ou une option CLI.'),
            'items' => [['CF', 'whole', 'Overview'], ['CF', 'keep', 'Override configuration']],
        ],
        'pages' => [
            'site' => ['w' => 1, 'title' => $t('Site options', 'Options du site'),
                'desc' => $t('title, baseurl, menus, taxonomies, theme, date, metatags, debug, etc.', 'title, baseurl, menus, taxonomies, theme, date, metatags, debug, etc.'),
                'items' => [['CF', 'whole', 'Options', ['language', 'languages']]]],
            'languages' => ['w' => 2, 'title' => $t('Languages', 'Langues'),
                'desc' => $t('Main language and additional languages of a multilingual website.', 'Langue principale et langues supplémentaires d’un site multilingue.'),
                'items' => [['CF', 'h3', 'Options', ['language', 'languages']]]],
            'locale-codes' => ['w' => 3, 'title' => $t('Locale codes', 'Codes de locale'),
                'desc' => $t('List of available locale codes to use with the languages option.', 'Liste des codes de locale à utiliser avec l’option languages.'),
                'items' => [['LOC', 'body']]],
            'pages' => ['w' => 4, 'title' => $t('Pages', 'Pages'),
                'desc' => $t('Pages directory, sorting, pagination, paths, body, virtual pages, generators, etc.', 'Dossier des pages, tri, pagination, chemins, corps, pages virtuelles, générateurs, etc.'),
                'items' => [['CF', 'whole', 'Pages']]],
            'data-static' => ['w' => 5, 'title' => $t('Data and static files', 'Données et fichiers statiques'),
                'desc' => $t('Data files and static files options.', 'Options des fichiers de données et des fichiers statiques.'),
                'items' => [['CF', 'keep', 'Data'], ['CF', 'keep', 'Static']]],
            'assets' => ['w' => 6, 'title' => $t('Assets', 'Assets'),
                'desc' => $t('Assets directory, compilation, minification, images and CDN.', 'Dossier des assets, compilation, minification, images et CDN.'),
                'items' => [['CF', 'whole', 'Assets']]],
            'layouts' => ['w' => 7, 'title' => $t('Layouts', 'Layouts'),
                'desc' => $t('Templates directory, auto-escaping, images, translations and components.', 'Dossier des templates, échappement, images, traductions et composants.'),
                'items' => [['CF', 'whole', 'Layouts']]],
            'output' => ['w' => 8, 'title' => $t('Output', 'Sortie'),
                'desc' => $t('Output directory, formats and post-processing.', 'Dossier de sortie, formats et post-traitement.'),
                'items' => [['CF', 'whole', 'Output']]],
            'cache' => ['w' => 9, 'title' => $t('Cache', 'Cache'),
                'desc' => $t('Assets, templates and translations cache.', 'Cache des assets, des templates et des traductions.'),
                'items' => [['CF', 'whole', 'Cache']]],
            'server' => ['w' => 10, 'title' => $t('Server and optimization', 'Serveur et optimisation'),
                'desc' => $t('Local server headers and output optimization.', 'En-têtes du serveur local et optimisation de la sortie.'),
                'items' => [['CF', 'keep', 'Server'], ['CF', 'keep', 'Optimize']]],
        ],
    ],
    'commands' => [
        'weight' => 6,
        'index' => [
            'title' => $t('Commands', 'Commandes'),
            'desc' => $t('Reference of Cecil CLI commands and options.', 'Référence des commandes et options de la CLI de Cecil.'),
            'items' => [['CM', 'pre']],
            'alias' => ['fr' => 'documentation/commandes'],
        ],
        'pages' => [
            'new-site' => ['w' => 1, 'title' => $t('new:site', 'new:site'), 'desc' => $t('Create a new website.', 'Créer un nouveau site.'), 'items' => [['CM', 'whole', 'new:site']]],
            'new-page' => ['w' => 2, 'title' => $t('new:page', 'new:page'), 'desc' => $t('Create a new page, optionally from a model.', 'Créer une nouvelle page, éventuellement à partir d’un modèle.'), 'items' => [['CM', 'whole', 'new:page']]],
            'serve' => ['w' => 3, 'title' => $t('serve', 'serve'), 'desc' => $t('Preview the website with the built-in server.', 'Prévisualiser le site avec le serveur intégré.'), 'items' => [['CM', 'whole', 'serve']]],
            'build' => ['w' => 4, 'title' => $t('build', 'build'), 'desc' => $t('Build the website.', 'Générer le site.'), 'items' => [['CM', 'whole', 'build']]],
            'doctor' => ['w' => 5, 'title' => $t('doctor', 'doctor'), 'desc' => $t('Diagnose the configuration, front matter and SEO.', 'Diagnostiquer la configuration, le front matter et le SEO.'), 'items' => [['CM', 'whole', 'doctor']]],
        ],
    ],
    'deploy' => [
        'weight' => 7,
        'index' => [
            'title' => $t('Deploy', 'Déployer'),
            'desc' => $t('Deploy your static website to Jamstack platforms, through continuous deployment or to a static hosting.', 'Déployez votre site statique sur des plateformes Jamstack, via le déploiement continu ou sur un hébergement statique.'),
            'items' => [['D', 'pre']],
            'alias' => $t('documentation/publish', ['documentation/publier', 'documentation/deployer']),
        ],
        'pages' => [
            'jamstack-platforms' => ['w' => 1, 'title' => $t('Jamstack platforms', 'Plateformes Jamstack'),
                'desc' => $t('Netlify, Vercel, statichost, Cloudflare Pages, Render.', 'Netlify, Vercel, statichost, Cloudflare Pages, Render.'),
                'items' => [['D', 'whole', 'Jamstack platforms']]],
            'continuous-deployment' => ['w' => 2, 'title' => $t('Continuous build & deploy', 'Build et déploiement continus'),
                'desc' => $t('GitHub Pages and GitLab CI.', 'GitHub Pages et GitLab CI.'),
                'items' => [['D', 'whole', 'Continuous build & deploy']]],
            'static-hosting' => ['w' => 3, 'title' => $t('Static hosting', 'Hébergement statique'),
                'desc' => $t('Deploy to a static hosting (Surge).', 'Déployer sur un hébergement statique (Surge).'),
                'items' => [['D', 'whole', 'Static hosting']]],
        ],
    ],
    'developers' => [
        'weight' => 8,
        'index' => [
            'title' => $t('Developers', 'Développeurs'),
            'desc' => $t('Extend Cecil with PHP, use it as a library and understand its architecture.', 'Étendez Cecil avec PHP, utilisez-le comme bibliothèque et comprenez son architecture.'),
            'text' => $t('For PHP developers: extend Cecil, use it as a library, and explore its internals and [API reference](/documentation/library/api/).', 'Pour les développeurs PHP : étendez Cecil, utilisez-le comme bibliothèque et explorez son fonctionnement interne et la [référence de l’API](/documentation/library/api/).'),
            'items' => [],
        ],
        'pages' => [
            'extend' => ['w' => 1, 'title' => $t('Extend', 'Étendre'),
                'desc' => $t('Create custom pages generators, add Twig extensions and post-process output files.', 'Créez des générateurs de pages, ajoutez des extensions Twig et post-traitez les fichiers de sortie.'),
                'items' => [['E', 'body']], 'alias' => $t('documentation/extend', 'documentation/etendre')],
            'library' => ['w' => 2, 'title' => $t('Library', 'Bibliothèque'),
                'desc' => $t('Use Cecil as a PHP library: install it with Composer, then build and diagnose programmatically.', 'Utilisez Cecil comme bibliothèque PHP : installez-le avec Composer, puis générez et diagnostiquez par programmation.'),
                'items' => [['L', 'body']], 'alias' => $t('documentation/library', 'documentation/bibliotheque')],
            'architecture' => ['w' => 3, 'title' => $t('Architecture', 'Architecture'),
                'desc' => $t('Diagram of the build pipeline and key components.', 'Diagramme du processus de génération et composants clés.'),
                'items' => [['A', 'body']], 'alias' => $t('documentation/architecture', 'documentation/architecture')],
        ],
    ],
];
