name: Scheduled Build
on:
  schedule:
    - cron: '0 7 * * *'
      timezone: "France/Paris"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -fsS -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}"
